### ISSUE TITLE
Nice tutorial but out of date.

### ISSUE THREAD

**Issue by stevenjowens** [alvinj/JavaPackagerTextArea#3]
Hi,

I tried to follow the tutorial but apparently jpackager has been deprecated, so you get this (frustratingly vague and misleading) error message:

"The operation couldn’t be completed. Unable to locate a Java Runtime that supports javapackager."

According to:
https://stackoverflow.com/questions/7633099/how-to-create-a-app-file-of-my-java-project-to-run-on-mac-os

"Javapackager is the packaging and signing tool released with JDK 8; When JDK 11 deleted javaFX, javapackager is also deleted as a part of it.

That's why you may encounter below issue when you try to use javapackager:

The operation couldn’t be completed. Unable to locate a Java Runtime that supports javapackager."

Apparently there's a new tool, "jpackage" (without the "r" on the end), but I'm still trying to figure out how to make that work.

**Comment by alvinj** [comment]
> Apparently there's a new tool, "jpackage"

Yeah, I’m sorry about the age of this, I need to do delete a lot of old blog posts and projects. But I wrote about `jpackage` with JDK 14 here: [alvinalexander.com/java/how-use-jpackage-command-java-14-jdk-sdk/](https://alvinalexander.com/java/how-use-jpackage-command-java-14-jdk-sdk/). I hope that helps.

**Comment by stevenjowens** [comment]
Thanks, I'll check it out!

**Comment by stevenjowens** [comment]
I suggest you'd be better off, rather than deleting that post, adding a note at the top and a link to the newer tutorial.

**Comment by alvinj** [comment]
Thanks for that. I just updated all of my old Mac/Java articles to link to the new one, so I’m going to close this issue. I appreciate your help!

**Comment by stevenjowens** [comment]
Yay!
